### ISSUE TITLE
Add the reference to integrity-checker to the documentation

### ISSUE THREAD

**Issue by aptrc** [swiss-ai-center/core-engine#126]
Could you add the reference of [integrity-checker](https://github.com/csia-pme/integrity-checker) to the official [documentation](https://csia-pme.github.io/csia-pme/reference/)?

**Comment by Emmanuel-desalis** [comment]
- Added integrity-checker.md in docs/reference
- Updated docs/reference/index.md with reference to integrity-checker
- Updated mkdocs.yml  with reference to integrity-checker
