### ISSUE TITLE
Rename the organization and repository

### ISSUE THREAD

**Issue by ludelafo** [swiss-ai-center/core-engine#131]
After a discussion between @aptrc and @henneber, it was decided to rename the CSIA-PME organization to Swiss AI Center and this repostory to `core-engine`.

This change will allow a consistency between the publications made in the medias (press, [website](https://www.hes-so.ch/swiss-ai-center), etc.) and the codebase.

@rmarquis, @leonardcser, @SimWalther: I am aware you are working for the GISCUP 2023. Would it be a problem if we rename the organization in the following days? It should only be a matter of updating your Git configuration file(s). Please let us know if we can proceed with the renaming

**Comment by rmarquis** [comment]
Not a problem. Thanks for the heads-up!
