### ISSUE TITLE
Project hosting / requirements for an infrastructure

### ISSUE THREAD

**Issue by ludelafo** [swiss-ai-center/core-engine#14]
# Current situation

The current infrastructure is not yet completely defined and some aspects needs to be improved.

We currently have access to the following items:

- A website to present the project is managed by the HES-SO
- A documentation website is hosted on GitHub Pages
- Two Kubernetes clusters hosted in Fribourg and Yverdon. The cluster from Fribourg is used to host the services, the engine and the webapp
- In the Kubernetes clusters, we have access to GPUs nodes to train our models and infer from them
- Both clusters have their own limitations in terms of external accesses (The Yverdon cluster is inaccessible without the VPN, to access the deployments on the Rancher WebUI, an account must be created by the cluster manager in Fribourg)

# Needs

For this project, we need:

- A Kubernetes cluster or Kubernetes namespace that we can manage entirely
  - A staging cluster for testing
  - A production cluster for production
  - At the moment, one possibility is to continue to use the Fribourg cluster for staging but a production-ready cluster hosted by a cloud provider would be nice
- Object storage system (S3) to store our data, models and other binary resources that is accessible externally (to train our models from GitHub Actions or any CI/CD tools)
  - At the moment, a MinIO instance is hosted by Fribourg for this purpose
- A Postgres database to store the Engine's data
  - At the moment, a virtual machine hosted by Fribourg is used for this purpose
 
All points listed must be accessible externally (WAN), except for the database.

# Alternatives to solve the problem

## Host our infrastructure on an external provider (Exoscale?)

As the current situation is mostly a testing/staging environment, it would be nice to have a production-ready environment.

## Split the infrastructure between multiple providers (HEIA-FR/HEIG-VD + Exoscale?)

We can also split the infrastructure to use multiple-sites machines. For example the MinIO can be in Yverdon while the Kubernetes cluster with the engine can be in Fribourg.

## Do not use Kubernetes to host all our core services (MinIO and Database externally and all ML services on Kubernertes)

One other solution is to use a VM dedicated to MinIO and another for Postgres. All the ML services can be hosted on the Kubernetes cluster. This is already the case but a production-ready environment would be more robust.

**Comment by ludelafo** [comment]
It seems we have settled with Kubernetes and Exoscale, maybe we can close this issue?

**Comment by andrptrc** [comment]
Closing this issue since we have the following infrastructure:

- Staging in Fribourg: k8s, object storage and PostgreSQL DB
- Production with Exoscale: k8s, object storage and PostgreSQL DB

Pricing on Exoscale will be calculated and we will define if the infrastructure is adapted to the project
