### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by ludelafo** [swiss-ai-center/core-engine#151]
- [x] State that the inputs/outputs of the services are in bytes
- [x] Add a schema of the different components (core-engine, webapp and services) and how their interact with each others
- [x] Rename the title "Test service" of the "Create a new service" tutorial to "Validate that you have everything working locally with Pytest" or something equivalent
- [x] Change the links that redirect to "Run core-engine in minikube" to "Run core-engine with Docker Compose" (related to #150)
- [x] Move the "Create a GitHub workflow" at the end of the tutorial and add an admonition to state that this step is only required if the reader wants to automatically deploy the service with GitHub Actions or GitLab CI (coming soon)
- [x] Fix the Kubernetes stateful snippets to have the updated file with the final name of the service for the tutorials "Implement a service with/without a model"
- [x] Fix highlight lines
- [x] Recheck all the documentation

**Comment by andrptrc** [comment]
Issues of missing elements/changes have been opened in documentation repo https://github.com/swiss-ai-center/documentation/issues/17 https://github.com/swiss-ai-center/documentation/issues/40
