### ISSUE TITLE
Refactor the Swiss AI Center GitHub organization

### ISSUE THREAD

**Issue by ludelafo** [swiss-ai-center/core-engine#156]
This issue is meant to track the changes made in the following issues:

- swiss-ai-center/core-engine#147
- swiss-ai-center/core-engine#149
- swiss-ai-center/documentation#1
- swiss-ai-center/core-engine#154
- swiss-ai-center/core-engine#155

The goal of this refactor is to help new comers to better understand the structure of our works, easily find examples they can use/get inspiration from and help write better and easier to understand documentation (related to swiss-ai-center/core-engine#150 and swiss-ai-center/core-engine#151).

**Comment by andrptrc** [comment]
All the changes have been made, there is still a little documentation to write.
